# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.8

# Command to install project dependencies
install:
  - pip3 install .
  - pip3 install -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script:
  - mypy . tests/*.py
  - black --check .
  - flake8 mcc.py tests
  - python3 -m unittest discover tests
